version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/frontend"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    open-pull-requests-limit: 15
  - package-ecosystem: gradle
    directory: "/backend"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    open-pull-requests-limit: 15
