apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: emottak-monitor
  namespace: default
  labels:
    team: team-emottak
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/dev/creds/emottak_q1-srvemottaknais
        mountPath: /secrets/emottak-monitor/credentials
      - kvPath: /azuread/data/dev/creds/emottak-monitor
        mountPath: /secrets/azuread/emottak-monitor
      - kvPath: /kv/preprod/fss/emottak-monitor/default
        mountPath: /secrets/default
  webproxy: true
  ingresses:
    - "https://emottak-monitor.nais.preprod.local"
  env:
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/.well-known/openid-configuration
    - name: JWT_ISSUER
      value: https://sts.windows.net/966ac572-f5b7-4bbe-aa88-c76419c0f851/
    - name: DATABASE_URL
      value: jdbc:oracle:thin:@a01dbfl033.adeo.no:1521/emottak_q1
    - name: DATABASE_PREFIX
      value: emottak_q1
    - name: EMOTTAK_ADMIN_FRONTEND_URL
      value: emottak-monitor-frontend.nais.preprod.local
    - name: EMOTTAK_AMDIN_CLIENT_PATH
      value: /secrets/azuread/emottak-monitor/client_id
    - name: OID_WELL_KNOWN_URI
      value: /secrets/default/oidcWellKnownUri
