apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "emottak-monitor-frontend"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/metrics"
  ingresses: 
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  tracing:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: emottak-monitor
          namespace: team-emottak
          cluster: dev-fss
    inbound:
      rules:
        - application: emottak-monitor
          namespace: team-emottak
          cluster: dev-fss
        - application: flex-fss-proxy
          namespace: flex
          cluster: dev-fss