apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "emottak-monitor-frontend"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  ingresses: 
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  azure:
    application:
      enabled: true
  elastic:
    instance: "emottak-monitor-frontend"