apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "emottak-monitor-frontend"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/metrics"
  ingresses: 
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  tracing:
    enabled: true

  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: false
      replyURLs:
        - 'https://emottak-monitor.dev.intern.nav.no/callback'
      claims:
        extra:
          - NAVident
        groups:
          - id: "0000-GA-Mottak-Monitor"
    vault:
      enabled: true
      paths:
        - kvPath: /kv/preprod/fss/emottak-monitor-frontend/team-emottak
          mountPath: /secrets/emottak-monitor-frontend
    webproxy: true
  accessPolicy:
    outbound:
      external:
        - host: https://emottak-monitor.dev.intern.nav.no
      rules:
        - application: emottak-monitor
          namespace: team-emottak
          cluster: dev-fss
