apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: emottak-monitor
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/prod/creds/emottak-srvemottaknais
        mountPath: /secrets/emottak-monitor/credentials
      - kvPath: /azuread/data/prod/creds/emottak-monitor
        mountPath: /secrets/azuread/emottak-monitor
      - kvPath: /kv/prod/fss/emottak-monitor/default
        mountPath: /secrets/default
  azure:
    application:
      enabled: true
      tenant: nav.no
  webproxy: true
  ingresses:
    - "https://emottak-monitor.intern.nav.no"
    - "https://emottak-monitor.prod-fss-pub.nais.io"
  env:
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration
    - name: JWT_ISSUER
      value: https://sts.windows.net/62366534-1ec3-4962-8869-9b5535279d0b/
    - name: DATABASE_URL
      value: jdbc:oracle:thin:@a01dbfl050.adeo.no:1521/emottak
    - name: DATABASE_PREFIX
      value: nmp5
    - name: EMOTTAK_ADMIN_FRONTEND_URL
      value: emottak-monitor-frontend.intern.nav.no
    - name: EMOTTAK_AMDIN_CLIENT_PATH
      value: /secrets/azuread/emottak-monitor/client_id
    - name: OID_WELL_KNOWN_URI
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
