apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: emottak-monitor
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/dev/creds/emottak_q1-srvemottaknais
        mountPath: /secrets/emottak-monitor/credentials
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  azure:
    application:
      enabled: true
#      tenant: nav.no
  webproxy: true
  ingresses:
    - "https://emottak-monitor.intern.dev.nav.no"
    - "https://emottak-monitor.dev-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: emottak-monitor-frontend
          namespace: team-emottak
          cluster: dev-gcp
    outbound:
      rules:
        - application: emottak-event-manager
          namespace: team-emottak
          cluster: dev-fss
  env:
#    - name: AADACCESSTOKEN_URL
#      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
#    - name: AADDISCOVERY_URL
#      value: https://login.microsoftonline.com/navq.onmicrosoft.com/.well-known/openid-configuration
#    - name: JWT_ISSUER
#      value: https://sts.windows.net/966ac572-f5b7-4bbe-aa88-c76419c0f851/

    - name: DATABASE_URL
      value: jdbc:oracle:thin:@dmv06-scan.adeo.no:1521/emottak_q1_ha
    - name: DATABASE_PREFIX
      value: nmt3
    - name: EMOTTAK_ADMIN_FRONTEND_URL
      value: emottak-monitor-frontend.intern.dev.nav.no
    - name: DEVELOPMENT
      value: "true"
    - name: AZURE_APP_EMOTTAK_CLIENT_ID
      value: 51c1af58-0676-4de7-aea0-60bc97208947
    - name: EVENT_MANAGER_URL
      value: https://emottak-event-manager.intern.dev.nav.no
