CREATE USER nmt2 
    IDENTIFIED BY out_standing1;
    
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_GRACE_TIME 1000;
GRANT CONNECT TO nmt2;
GRANT CREATE SESSION TO nmt2;
GRANT UNLIMITED TABLESPACE TO nmt2;
GRANT SELECT ANY TABLE TO nmt2;
GRANT SELECT ANY DICTIONARY to nmt2;
GRANT LOCK ANY TABLE to nmt2;