WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."ABONNEMENT";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."ACTIONCONTEXT";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."ADAPTER";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."ALTINN_ARCHIVE_RECEIPT";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."ALTINN_SHIPMENT";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."ALTINN_TRANSPORT_RECEIPT";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."COLLABROLECONTROLLER";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."DESTINASJON";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."DIALOG";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."HENDELSE";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."INN_KONVOLUTT";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."JOBB_MOTTAKER";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."KOMMUNIKASJONSSYSTEM";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."LAGRETMELDING";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."LOGG";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."MELDING";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."PARTNER";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."PARTNER_CPA";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."PARTNER_JOBB";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."PARTNER_MAPPING";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."PARTY_ID_TYPE";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."RESENDING";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."RESENDING_CONFIG";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."SCENARIO";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."SERVICE_DEPENDENCY";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."SKJEMAREGEL";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."BATCH";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."BATCH_JOB_EXECUTION";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."BATCH_JOB_EXECUTION_CONTEXT";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."BATCH_JOB_INSTANCE";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."BATCH_JOB_PARAMS";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."BATCH_STEP_EXECUTION";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."BATCH_STEP_EXECUTION_CONTEXT";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."SSNCACHE";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."STATUS";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."SUBMITFORMTASK";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."TJENESTE";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."TJENESTE_ACTIONCONTEXT";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."EBREV";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."EBREV_ABONNEMENT";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."EBREV_BREVKODE";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."EGENANDEL_LOGG";
WHENEVER SQLERROR CONTINUE NONE
DROP TABLE "NMT2"."PASIENT_LISTE";