CREATE TABLE "NMT2"."ALTINN_ARCHIVE_RECEIPT"
(
    SHIPMENT_REFERENCE NUMBER PRIMARY KEY NOT NULL,
    TIME_DATE varchar2(40),
    ARCHIVE_REFERENCE varchar2(100) NOT NULL
);

CREATE TABLE "NMT2"."ALTINN_SHIPMENT"
(
    SHIPMENT_REFERENCE NUMBER PRIMARY KEY NOT NULL,
    BATCH_NR NUMBER,
    TERM_YEAR varchar2(7),
    TIME_DATE varchar2(40),
    ORG_NR NUMBER,
    FILE_NAME varchar2(40)
);

CREATE TABLE "NMT2"."ALTINN_TRANSPORT_RECEIPT"
(
    SHIPMENT_REFERENCE NUMBER PRIMARY KEY NOT NULL,
    RECEIPT_ID NUMBER NOT NULL
);

