CREATE TABLE "NMT2"."DESTINASJON"
(
    DEST_ID NUMBER PRIMARY KEY NOT NULL,
    TRGT_REF varchar2(50) NOT NULL,
    TRGTBESKR varchar2(80) NOT NULL
);
CREATE UNIQUE INDEX TRGTREF_UNIQUE ON "DESTINASJON"(TRGT_REF);

INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (73,'BRUKES_IKKE','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (74,'MELDING_DEAD','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (75,'EBXML_INNPOST','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (76,'EBXML_INNPOST_APOK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (77,'EBXML_INNPOST_CPP','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (78,'EBXML_INNPOST_FOM','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (79,'EBXML_INNPOST_EDI_SMLE','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (80,'EBXML_INNPOST_EDI_APOK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (81,'EBXML_INNPOST_ALTIN','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (82,'EBXML_INNPOST_RESEPT','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (83,'EBXML_INNPOST_ORTOK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (84,'EBXML_INNPOST_POLK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (85,'EBXML_INNPOST_LABRONK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (87,'EDI_INNPOST_POLK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (88,'EDI_INNPOST_LABRONK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (90,'EDI_KRYPTERT_INNPOST','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (91,'KONTROLL_MELDINGER','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (92,'KONTROLL_OPPGJOR','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (93,'APOK_MELDING_TIL_KONTROLL','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (94,'FOM_KONTROLL','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (95,'RESEPT_KONTROLL','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (96,'BRUKERBESTILLING_TIL_INFOTRYGD','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (97,'ALTINN_ACK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (98,'FASTLEGE_ACK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (99,'RESEPT_ACK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (100,'EBXML_UTPOST','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (101,'HELSEKORTBESTILLINGFLATFIL','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (102,'UTSENDING','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (103,'EHIC_ACK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (104,'EBXML_INBOUND','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (121,'RESEPT_APPREC','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (141,'RESEPT_APPREC_V2','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (142,'RESEPT_KONTROLL_V2','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (161,'EIA2_MELDINGER','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (181,'EBXML_INNPOST_TJENESTE','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (182,'TOKT_MOTTAK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (201,'RESEPT_M2','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (221,'EBXML_SYNKRON_INNPOST','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (222,'TOKT_EGENANDEL','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (223,'EBXML_SYNKRON_UTPOST','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (224,'INNRAPP_TREKK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (225,'TOKT_EBREV_INN','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (226,'TOKT_FASTLEGE_INN','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (229,'TOKT_PASIENTLISTE_INN','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (230,'TOKT_EGENANDEL_MENGDE','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (231,'TOKT_ASYNKRON_INN','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (251,'SI_STATUS_REPLY','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (252,'EM_STATUS_REPLY','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (291,'ELETTER_ACK','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (311,'TOKT_EGENANDEL_FRIKORT','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (312,'TOKT_EGENANDEL_PENSJON','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (331,'RESEPT_M30','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (332,'OEBS_M30N_APPREC','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (351,'EIA_ONLINE_MELDINGER','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (371,'AAREG_INN','Arbeidsgiver- og arbeidstagerregisteret');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (391,'INNTEKT_KOMMUNE','Inntektsforespørsel fra kommunene');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (392,'HDIR','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (411,'INNTEKTSKOMP','Inntektskomponenten');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (431,'AMELDING_REQUEST','innsending av a-melding');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (432,'AMELDING_RESPONSE','a-melding tilbakemelding');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (451,'DVH_MAALEKORT','Kø for resultatrapport');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (471,'PALE_INPUT','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (580,'DIALOGFORDELER_DIALOGMELDINGER','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (581,'SYFO_DIALOG_INPUT','NA');
INSERT INTO "NMT2"."DESTINASJON" (DEST_ID,TRGT_REF,TRGTBESKR) VALUES (888,'SYFOMOTTAK_INPUT','NA');

