CREATE TABLE "NMT2"."KOMMUNIKASJONSSYSTEM"
(
    KOMMUNIKASJONSSYSTEM_ID NUMBER PRIMARY KEY NOT NULL,
    BESKRIVELSE varchar2(255) NOT NULL
);


INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (0,'Ukjent');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (1,'DIPS Communicator');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (2,'Medilink');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (3,'Infodoc');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (4,'Visma Link');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (5,'Communicate');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (6,'Hermes');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (7,'TerminalOne Transport');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (8,'Arkensoftware');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (9,'Covast');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (10,'WebMethods');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (11,'Compugroupmedical');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (12,'Apertura');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (13,'OpusDental');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (14,'Teito');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (15,'Aspit');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (31,'ProMed');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (32,'Acos');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (33,'Farmait');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (34,'Boots');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (54,'VAF');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (74,'Espire');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (94,'HELSEDIREKTORATET');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (114,'Hemit');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (134,'Enableit');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (154,'ApotekProsjekt');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (155,'PVF');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (174,'patientsky');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (194,'Helse Vest IKT');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (214,'Somasolutions');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (234,'Avans');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (254,'Thula');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (274,'Sykehuspartner');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (294,'Unilabs');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (314,'AnitaSystem');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (334,'Apotek1');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (354,'CAPGEMINI NORGE AS');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (374,'Sykehus Klinikker');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (394,'eHelse');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (414,'bitt');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (434,'Skogli');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (454,'Furst');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (474,'FarmaProd');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (494,'Nytt Nav Cert');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (514,'Pridok');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (534,'Helse Nord IKT');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (554,'NHN');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (574,'Webmed');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (594,'Sogeti');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (614,'NMD');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (634,'Liaison');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (654,'Extensor');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (674,'McKesson');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (694,'Helseplattformen');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (714,'unisoft');
INSERT INTO "NMT2"."KOMMUNIKASJONSSYSTEM" (KOMMUNIKASJONSSYSTEM_ID,BESKRIVELSE) VALUES (734,'Sykehusapotekene HF');
