CREATE TABLE "NMT2"."RESENDING"
(
    RESENDING_ID varchar2(50) PRIMARY KEY NOT NULL,
    TIME_SENT timestamp NOT NULL,
    RETRIES_REMAINING NUMBER NOT NULL,
    RETRY_INTERVAL NUMBER NOT NULL,
    NEXT_RETRY timestamp NOT NULL,
    NODE varchar2(200)
);

CREATE TABLE "NMT2"."RESENDING_CONFIG"
(
    ROLE varchar2(50) NOT NULL,
    SERVICE varchar2(50) NOT NULL,
    ACTION varchar2(50) NOT NULL,
    MAX_RETRIES NUMBER NOT NULL,
    RETRY_INTERVAL NUMBER NOT NULL,
    CONSTRAINT RESENDING_CONFIG_ID PRIMARY KEY (ROLE,SERVICE,ACTION)
);


INSERT INTO "NMT2"."RESENDING_CONFIG" (ROLE,SERVICE,ACTION,MAX_RETRIES,RETRY_INTERVAL) VALUES ('Behandler','IndividuellRefusjon','Kvittering',5,3600000);
INSERT INTO "NMT2"."RESENDING_CONFIG" (ROLE,SERVICE,ACTION,MAX_RETRIES,RETRY_INTERVAL) VALUES ('Behandler','IndividuellRefusjon','Soknad',5,3600000);
INSERT INTO "NMT2"."RESENDING_CONFIG" (ROLE,SERVICE,ACTION,MAX_RETRIES,RETRY_INTERVAL) VALUES ('DEFAULT','DEFAULT','DEFAULT',5,3600000);
