CREATE TABLE "NMT2"."SSNCACHE"
(
    SUBJECTDN varchar2(1024) NOT NULL,
    FNR varchar2(50) NOT NULL,
    OPPDATERT timestamp NOT NULL,
    ISSUERDN varchar2(1024) NOT NULL,
    SERIALNUMBER varchar2(30) PRIMARY KEY NOT NULL
);

