CREATE TABLE "NMT2"."BATCH"
(
    NAME varchar2(20) PRIMARY KEY NOT NULL,
    RUNNING NUMBER NOT NULL,
    LASTRUN timestamp
);

CREATE TABLE "NMT2"."BATCH_JOB_EXECUTION"
(
    JOB_EXECUTION_ID NUMBER PRIMARY KEY NOT NULL,
    VERSION NUMBER,
    JOB_INSTANCE_ID NUMBER NOT NULL,
    CREATE_TIME timestamp NOT NULL,
    START_TIME timestamp DEFAULT NULL,
    END_TIME timestamp DEFAULT NULL,
    STATUS varchar2(10),
    EXIT_CODE varchar2(100),
    EXIT_MESSAGE varchar2(2500),
    LAST_UPDATED timestamp
);
ALTER TABLE "NMT2"."BATCH_JOB_EXECUTION"
    ADD CONSTRAINT JOB_INST_EXEC_FK
        FOREIGN KEY (JOB_INSTANCE_ID)
            REFERENCES "BATCH_JOB_INSTANCE"(JOB_INSTANCE_ID);

CREATE TABLE "NMT2"."BATCH_JOB_EXECUTION_CONTEXT"
(
    JOB_EXECUTION_ID NUMBER PRIMARY KEY NOT NULL,
    SHORT_CONTEXT varchar2(2500) NOT NULL,
    SERIALIZED_CONTEXT clob
);
ALTER TABLE "NMT2"."BATCH_JOB_EXECUTION_CONTEXT"
    ADD CONSTRAINT JOB_EXEC_CTX_FK
        FOREIGN KEY (JOB_EXECUTION_ID)
            REFERENCES "BATCH_JOB_EXECUTION"(JOB_EXECUTION_ID);

CREATE TABLE "NMT2"."BATCH_JOB_INSTANCE"
(
    JOB_INSTANCE_ID NUMBER PRIMARY KEY NOT NULL,
    VERSION NUMBER,
    JOB_NAME varchar2(100) NOT NULL,
    JOB_KEY varchar2(32) NOT NULL
);
CREATE UNIQUE INDEX JOB_INST_UN ON "BATCH_JOB_INSTANCE"
(
  JOB_NAME,
  JOB_KEY
);

CREATE TABLE "NMT2"."BATCH_JOB_PARAMS"
(
    JOB_INSTANCE_ID NUMBER NOT NULL,
    TYPE_CD varchar2(6) NOT NULL,
    KEY_NAME varchar2(100) NOT NULL,
    STRING_VAL varchar2(250),
    DATE_VAL timestamp DEFAULT NULL,
    LONG_VAL NUMBER,
    DOUBLE_VAL NUMBER
);
ALTER TABLE "NMT2"."BATCH_JOB_PARAMS"
    ADD CONSTRAINT JOB_INST_PARAMS_FK
        FOREIGN KEY (JOB_INSTANCE_ID)
            REFERENCES "BATCH_JOB_INSTANCE"(JOB_INSTANCE_ID);

CREATE TABLE "NMT2"."BATCH_STEP_EXECUTION"
(
    STEP_EXECUTION_ID NUMBER PRIMARY KEY NOT NULL,
    VERSION NUMBER NOT NULL,
    STEP_NAME varchar2(100) NOT NULL,
    JOB_EXECUTION_ID NUMBER NOT NULL,
    START_TIME timestamp NOT NULL,
    END_TIME timestamp DEFAULT NULL,
    STATUS varchar2(10),
    COMMIT_COUNT NUMBER,
    READ_COUNT NUMBER,
    FILTER_COUNT NUMBER,
    WRITE_COUNT NUMBER,
    READ_SKIP_COUNT NUMBER,
    WRITE_SKIP_COUNT NUMBER,
    PROCESS_SKIP_COUNT NUMBER,
    ROLLBACK_COUNT NUMBER,
    EXIT_CODE varchar2(100),
    EXIT_MESSAGE varchar2(2500),
    LAST_UPDATED timestamp
);
ALTER TABLE "NMT2"."BATCH_STEP_EXECUTION"
    ADD CONSTRAINT JOB_EXEC_STEP_FK
        FOREIGN KEY (JOB_EXECUTION_ID)
            REFERENCES "BATCH_JOB_EXECUTION"(JOB_EXECUTION_ID);

CREATE TABLE "NMT2"."BATCH_STEP_EXECUTION_CONTEXT"
(
    STEP_EXECUTION_ID NUMBER PRIMARY KEY NOT NULL,
    SHORT_CONTEXT varchar2(2500) NOT NULL,
    SERIALIZED_CONTEXT clob
);
ALTER TABLE "NMT2"."BATCH_STEP_EXECUTION_CONTEXT"
    ADD CONSTRAINT STEP_EXEC_CTX_FK
        FOREIGN KEY (STEP_EXECUTION_ID)
            REFERENCES "BATCH_STEP_EXECUTION"(STEP_EXECUTION_ID);
