CREATE TABLE "NMT2"."STATUS"
(
    STATUSLEVEL NUMBER PRIMARY KEY NOT NULL,
    STATUSTEXT varchar2(50)
);


INSERT INTO "NMT2"."STATUS" (STATUSLEVEL,STATUSTEXT) VALUES (0,'Opprettet');
INSERT INTO "NMT2"."STATUS" (STATUSLEVEL,STATUSTEXT) VALUES (10,'Informasjon');
INSERT INTO "NMT2"."STATUS" (STATUSLEVEL,STATUSTEXT) VALUES (15,'Manuell behandling');
INSERT INTO "NMT2"."STATUS" (STATUSLEVEL,STATUSTEXT) VALUES (20,'Advarsel');
INSERT INTO "NMT2"."STATUS" (STATUSLEVEL,STATUSTEXT) VALUES (30,'Feil');
INSERT INTO "NMT2"."STATUS" (STATUSLEVEL,STATUSTEXT) VALUES (40,'Fatal feil');
INSERT INTO "NMT2"."STATUS" (STATUSLEVEL,STATUSTEXT) VALUES (50,'Ferdigbehandlet');
