CREATE TABLE "NMT2"."SUBMITFORMTASK"
(
    MOTTAK_ID varchar2(64) PRIMARY KEY NOT NULL,
    TIME_SENT timestamp NOT NULL,
    RETRIES_REMAINING NUMBER NOT NULL,
    RETRY_INTERVAL NUMBER NOT NULL,
    NEXT_RETRY timestamp NOT NULL,
    EXTERNAL_SHIPMENT_REFERENCE varchar2(512),
    ARCHIVE_REFERENCE varchar2(512),
    RECEIVERS_REFERENCE NUMBER,
    HEADER_XML clob NOT NULL
);
CREATE INDEX INDXSBMTFRMTSKNXTRTR ON "SUBMITFORMTASK"(NEXT_RETRY);
CREATE INDEX INDXSBMTFRMTSKRTRRMN ON "SUBMITFORMTASK"(RETRIES_REMAINING);
