CREATE TABLE "NMT2"."JOBB_MOTTAKER"
(
    JM_ID varchar2(50) PRIMARY KEY NOT NULL,
    MOTTAK_ID varchar2(50) NOT NULL,
    JOBB_ID varchar2(80) NOT NULL,
    DATO_OPPRETTET timestamp
);
ALTER TABLE "NMT2"."JOBB_MOTTAKER"
    ADD CONSTRAINT JOBB_MOTTAKER_MOTTAK_ID
        FOREIGN KEY (MOTTAK_ID)
            REFERENCES "MELDING"(MOTTAK_ID);
ALTER TABLE "NMT2"."JOBB_MOTTAKER"
    ADD CONSTRAINT JOBB_MOTTAKER_JOBB_ID
        FOREIGN KEY (JOBB_ID)
            REFERENCES "PARTNER_JOBB"(JOBB_ID);
