CREATE TABLE "NMT2"."LAGRETMELDING"
(
    MOTTAK_ID varchar2(50) NOT NULL,
    DATOMOTTAT timestamp NOT NULL,
    MELDINGREF varchar2(256) NOT NULL,
    CONSTRAINT LAGRETMELDING PRIMARY KEY (MOTTAK_ID,DATOMOTTAT)
);
ALTER TABLE "NMT2"."LAGRETMELDING"
    ADD CONSTRAINT LAGRETMELDING_MELDING
        FOREIGN KEY (MOTTAK_ID)
            REFERENCES "MELDING"(MOTTAK_ID);
