  CREATE TABLE if not exists HENDELSE
  (
      HENDELSE_ID NUMBER(10,0),
      HENDELSEDESKR VARCHAR2(100),
      DISPOSABLE NUMBER(1,0) DEFAULT 0,
      STATUSLEVEL NUMBER(2,0) DEFAULT 0
      );

  CREATE TABLE if not exists LOGG
   (	LOGG_ID NUMBER(10,0), 
	MOTTAK_ID VARCHAR2(50), 
	HENDELSE_ID NUMBER(10,0), 
	TILLEGSINFO VARCHAR2(3000), 
	HENDELSEDATO TIMESTAMP (6), 
	STATUSLEVEL NUMBER(2,0) DEFAULT 0
   );

  CREATE TABLE if not exists MELDING
   (	MOTTAK_ID VARCHAR2(50), 
	AVTALE_ID VARCHAR2(50), 
	SERVICE VARCHAR2(50), 
	ACTION VARCHAR2(50), 
	EBCOMNAVN VARCHAR2(255), 
	EBCONVERS_ID VARCHAR2(80), 
	EBMESAGE_ID VARCHAR2(80), 
	EBTIMESTAMP TIMESTAMP (6), 
	MELDINGSPARAM VARCHAR2(255), 
	AVSENDERPARAM VARCHAR2(255), 
	REFERANSEPARAM VARCHAR2(255), 
	DATOMOTTAT TIMESTAMP (6), 
	CERTDN VARCHAR2(1024), 
	TRUSTDN VARCHAR2(1024), 
	DOCSIGNERDN VARCHAR2(1024), 
	REF2_MOTTAK_ID VARCHAR2(50), 
	REF2_EBMESAGE_ID VARCHAR2(80), 
	CORRELATION_ID VARCHAR2(255), 
	ROLE VARCHAR2(50) DEFAULT 'DEFAULT_VAL', 
	DOCSIGNERISSUERDN VARCHAR2(1024), 
	SYNKRON NUMBER(1,0) DEFAULT 0, 
	ACTIONCONTEXT VARCHAR2(50), 
	STATUSLEVEL NUMBER(2,0) DEFAULT 0
   );

  CREATE TABLE if not exists STATUS
  (	STATUSLEVEL NUMBER(2,0),
       STATUSTEXT VARCHAR2(50)
  );
