name: Build

on:
  pull_request:

env:
  "IMAGE":
    "docker.pkg.github.com/${{ github.repository }}/emottak-monitor-frontend:${{\
    \ github.sha }}"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"
      - name: Install node dependencies
        run: yarn
      - name: Build app with yarn
        run: yarn build
      - name: Build Docker image
        run: docker build --pull --tag ${IMAGE} .
