name: Build & deploy emottak-monitor-frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment to deploy"
        required: true
        default: "dev-fss"
        type: choice
        options:
          - dev-fss
          - prod-fss
  push:
    branches:
    - main
    paths-ignore:
    - ".github/workflows/backend.yaml"
    - "backend/**"
    - .envrc
    - "**/flake*"
    - "**/README.md"

jobs:
  test_and_build_and_deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Set-up git repo for frontend tests & build
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: cd frontend && yarn install --frozen-lockfile

      - name: 'Get current date'
        id: date
        run: echo "date=$(date +'%Y.%m.%d-%H.%M')" >> $GITHUB_OUTPUT

      - name: 'Set version in index.html'
        run: sed -i "s/__VERSION__/${{ steps.date.outputs.date }}/g" frontend/index.html

      # Build & test frontend + Docker Image
      - name: 'yarn build'
        run: cd frontend && yarn build

      - name: 'Build Docker Image'
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: team-emottak # required
          pull: true # optional, default false
          dockerfile: frontend/Dockerfile # optional, default Dockerfile
          docker_context: frontend/ # optional, default .
          image_suffix: frontend # optional, default empty
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret
          salsa: true # optional, default true, generates a attestation for the image

      - name: 'Deploy to dev'
        if: ${{ inputs.environment == 'dev-fss' }}
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ steps.docker-push.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: frontend/.nais/nais.yaml
          VARS: frontend/.nais/dev.yaml

      - name: 'Deploy to prod'
        if: ${{ inputs.environment == 'prod-fss' }}
        uses: nais/deploy/actions/deploy@v2
        env:
           IMAGE: ${{ steps.docker-push.outputs.image }}
           APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
           CLUSTER: prod-gcp
           RESOURCE: frontend/.nais/nais.yaml
           VARS: frontend/.nais/prod.yaml

