name: Build & deploy emottak-monitor-frontend

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - ".github/workflows/backend.yaml"
    - "backend/**"
    - .envrc
    - "**/flake*"
    - "**/README.md"

jobs:
  test_and_build_and_deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Set-up git repo for frontend tests & build
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: cd frontend && yarn install --frozen-lockfile

      # Build & test frontend + Docker Image
      - run: cd frontend && yarn build
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: team-emottak # required
          pull: true # optional, default false
          dockerfile: frontend/Dockerfile # optional, default Dockerfile
          docker_context: frontend/ # optional, default .
          image_suffix: frontend # optional, default empty
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret
          salsa: true # optional, default true, generates a attestation for the image

      # Deloy to dev
      - uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ steps.docker-push.outputs.image }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: frontend/.nais/nais.yaml
          VARS: frontend/.nais/dev.yaml

      # Deloy to prod
      - uses: nais/deploy/actions/deploy@v2
        env:
           IMAGE: ${{ steps.docker-push.outputs.image }}
           APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
           CLUSTER: prod-gcp
           RESOURCE: frontend/.nais/nais.yaml
           VARS: frontend/.nais/prod.yaml

