ingresses:
  - "https://emottak-monitor-frontend.intern.dev.nav.no"
  - "https://emottak-monitor.ansatt.dev.nav.no"
backend:
  host: "emottak-monitor-backend.dev-fss-pub.nais.io"
  cluster: dev-fss
url:
  react_app_url: "https://emottak-monitor-backend.dev-fss-pub.nais.io"
