apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "emottak-monitor-frontend"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/metrics"
  ingresses: 
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      tenant: {{allowedUsers.tenant}}
      allowAllUsers: false
      replyURLs:
        - {{ url.reply_url }}
      claims:
        extra:
          - NAVident
        groups:
          - id: {{allowedUsers.groupid}}
  accessPolicy:
    outbound:
      external:
        - host: {{backend.host}}
      rules:
        - application: emottak-monitor
          namespace: team-emottak
          cluster: {{backend.cluster}}
  env:
    - name: REACT_APP_URL
      value: {{url.react_app_url}}
    - name: PROXY_URL
      value: {{url.proxy_url}}
