ingresses:
  - "https://emottak-monitor-frontend.intern.nav.no"
  - "https://emottak-monitor.ansatt.nav.no"

backend:
  host: "emottak-monitor.prod-fss-pub.nais.io"
  cluster: prod-fss
url:
  react_app_url: "https://emottak-monitor.prod-fss-pub.nais.io"
  proxy_url: "https://emottak-monitor.intern.nav.no"
  reply_url: "https://emottak-monitor.intern.nav.no/callback"
